# Включить или отключить белый список
enabled: false

# Сообщение при кике, когда игрока нет в белом списке
kick_message: "&#f5222fВас нет в белом списке!"

# НЕ ТРОГАТЬ!!!
# Добавлять только командами
whitelist:
  - admin